### ISSUE TITLE
edit_creator script does not produce edits for case errors

### ISSUE THREAD

**Issue by kavehtp** [nusnlp/m2scorer#4]
Apparently, the edit_creator.py does not generate edits for case errors:

Source: As times pass by , My eyes went down the table below .
target: As time passed , my eyes went down the table below .

Result:

S As times pass by , My eyes went down the table below .
A 1 4|||UNK|||time passed|||REQUIRED|||-NONE-|||0

**Comment by tamhd** [comment]
I accidentally set ignore_whitespace_casing=True by default. It is 'False' by default now, to ignore casing, use flag: --ignore_whitespace_casing
